data = [
    {"name": "Cristiano Ronaldo", "follower_count": 635, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 520, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 430, "description": "Singer and actress", "country": "USA"},
    {"name": "Kylie Jenner", "follower_count": 410, "description": "Reality TV star and businesswoman", "country": "USA"},
    {"name": "Dwayne Johnson", "follower_count": 400, "description": "Actor and pro wrestler", "country": "USA"},
    {"name": "Ariana Grande", "follower_count": 390, "description": "Singer and actress", "country": "USA"},
    {"name": "Kim Kardashian", "follower_count": 370, "description": "Reality TV star and businesswoman", "country": "USA"},
    {"name": "Beyoncé", "follower_count": 320, "description": "Singer and actress", "country": "USA"},
    {"name": "Khloe Kardashian", "follower_count": 310, "description": "Reality TV star", "country": "USA"},
    {"name": "Nike", "follower_count": 300, "description": "Sports brand", "country": "USA"},
    {"name": "Justin Bieber", "follower_count": 290, "description": "Singer", "country": "Canada"},
    {"name": "Kendall Jenner", "follower_count": 280, "description": "Model", "country": "USA"},
    {"name": "National Geographic", "follower_count": 270, "description": "Magazine", "country": "USA"},
    {"name": "Taylor Swift", "follower_count": 260, "description": "Singer-songwriter", "country": "USA"},
    {"name": "Virat Kohli", "follower_count": 255, "description": "Cricketer", "country": "India"},
    {"name": "Jennifer Lopez", "follower_count": 240, "description": "Singer and actress", "country": "USA"},
    {"name": "Nicki Minaj", "follower_count": 230, "description": "Rapper", "country": "USA"},
    {"name": "Zendaya", "follower_count": 225, "description": "Actress and singer", "country": "USA"},
    {"name": "Drake", "follower_count": 220, "description": "Rapper", "country": "Canada"},
    {"name": "LeBron James", "follower_count": 210, "description": "Basketball player", "country": "USA"},
    {"name": "Kourtney Kardashian", "follower_count": 200, "description": "Reality TV star", "country": "USA"},
    {"name": "Cardi B", "follower_count": 195, "description": "Rapper", "country": "USA"},
    {"name": "Real Madrid", "follower_count": 190, "description": "Football Club", "country": "Spain"},
    {"name": "FC Barcelona", "follower_count": 185, "description": "Football Club", "country": "Spain"},
    {"name": "Billie Eilish", "follower_count": 180, "description": "Singer", "country": "USA"},
    {"name": "Emma Watson", "follower_count": 175, "description": "Actress and activist", "country": "UK"},
    {"name": "Shakira", "follower_count": 170, "description": "Singer", "country": "Colombia"},
    {"name": "Chris Hemsworth", "follower_count": 165, "description": "Actor", "country": "Australia"},
    {"name": "NASA", "follower_count": 160, "description": "Space agency", "country": "USA"},
    {"name": "Vin Diesel", "follower_count": 155, "description": "Actor", "country": "USA"},
    {"name": "Zlatan Ibrahimović", "follower_count": 150, "description": "Footballer", "country": "Sweden"},
    {"name": "Gigi Hadid", "follower_count": 145, "description": "Model", "country": "USA"},
    {"name": "Huda Kattan", "follower_count": 140, "description": "Beauty influencer", "country": "USA"},
    {"name": "Gal Gadot", "follower_count": 138, "description": "Actress", "country": "Israel"},
    {"name": "Will Smith", "follower_count": 135, "description": "Actor and rapper", "country": "USA"},
    {"name": "Camila Cabello", "follower_count": 130, "description": "Singer", "country": "USA"},
    {"name": "Snoop Dogg", "follower_count": 128, "description": "Rapper", "country": "USA"},
    {"name": "David Beckham", "follower_count": 125, "description": "Footballer", "country": "UK"},
    {"name": "BLACKPINK", "follower_count": 120, "description": "K-pop group", "country": "South Korea"},
    {"name": "RM (BTS)", "follower_count": 118, "description": "K-pop artist", "country": "South Korea"},
    {"name": "Jungkook", "follower_count": 115, "description": "K-pop artist", "country": "South Korea"},
    {"name": "Lisa (BLACKPINK)", "follower_count": 110, "description": "K-pop artist", "country": "Thailand"},
    {"name": "Dua Lipa", "follower_count": 108, "description": "Singer", "country": "UK"},
    {"name": "Shawn Mendes", "follower_count": 105, "description": "Singer", "country": "Canada"},
    {"name": "Priyanka Chopra", "follower_count": 102, "description": "Actress", "country": "India"},
    {"name": "Kevin Hart", "follower_count": 100, "description": "Comedian and actor", "country": "USA"},
    {"name": "Miley Cyrus", "follower_count": 98, "description": "Singer and actress", "country": "USA"},
    {"name": "Blake Lively", "follower_count": 96, "description": "Actress", "country": "USA"},
    {"name": "Robert Downey Jr.", "follower_count": 94, "description": "Actor", "country": "USA"},
    {"name": "Anitta", "follower_count": 92, "description": "Singer", "country": "Brazil"},
    {"name": "Luis Suarez", "follower_count": 90, "description": "Footballer", "country": "Uruguay"},
    {"name": "Paris Hilton", "follower_count": 88, "description": "Celebrity and businesswoman", "country": "USA"},
    {"name": "Maluma", "follower_count": 86, "description": "Singer", "country": "Colombia"},
    {"name": "Tyga", "follower_count": 85, "description": "Rapper", "country": "USA"},
    {"name": "Tom Holland", "follower_count": 83, "description": "Actor", "country": "UK"},
    {"name": "Rihanna", "follower_count": 80, "description": "Singer and businesswoman", "country": "Barbados"},
    {"name": "Travis Scott", "follower_count": 78, "description": "Rapper", "country": "USA"},
    {"name": "Millie Bobby Brown", "follower_count": 76, "description": "Actress", "country": "UK"},
    {"name": "Jason Statham", "follower_count": 74, "description": "Actor", "country": "UK"},
    {"name": "Bruno Mars", "follower_count": 72, "description": "Singer", "country": "USA"},
    {"name": "The Weeknd", "follower_count": 70, "description": "Singer", "country": "Canada"},
    {"name": "Jackie Chan", "follower_count": 68, "description": "Actor and martial artist", "country": "Hong Kong"},
    {"name": "Gordon Ramsay", "follower_count": 65, "description": "Chef and TV personality", "country": "UK"},
    {"name": "KSI", "follower_count": 64, "description": "YouTuber and boxer", "country": "UK"},
    {"name": "PewDiePie", "follower_count": 63, "description": "YouTuber", "country": "Sweden"},
    {"name": "MrBeast", "follower_count": 62, "description": "YouTuber", "country": "USA"},
    {"name": "Neymar Jr.", "follower_count": 280, "description": "Footballer", "country": "Brazil"},
    {"name": "Taehyung (V)", "follower_count": 60, "description": "K-pop artist", "country": "South Korea"},
    {"name": "IU", "follower_count": 58, "description": "Singer and actress", "country": "South Korea"},
    {"name": "Baekhyun", "follower_count": 55, "description": "K-pop artist", "country": "South Korea"},
    {"name": "Jisoo", "follower_count": 54, "description": "K-pop artist", "country": "South Korea"},
    {"name": "Rosé", "follower_count": 53, "description": "K-pop artist", "country": "New Zealand"},
    {"name": "Doja Cat", "follower_count": 52, "description": "Singer", "country": "USA"},
    {"name": "Charli D'Amelio", "follower_count": 50, "description": "TikTok star", "country": "USA"},
    {"name": "Addison Rae", "follower_count": 48, "description": "TikTok star", "country": "USA"},
    {"name": "James Charles", "follower_count": 47, "description": "Makeup artist", "country": "USA"},
    {"name": "Noah Beck", "follower_count": 45, "description": "TikTok star", "country": "USA"},
    {"name": "Dixie D'Amelio", "follower_count": 44, "description": "Singer and influencer", "country": "USA"},
    {"name": "Bella Poarch", "follower_count": 43, "description": "TikTok star", "country": "Philippines"},
    {"name": "Zach King", "follower_count": 42, "description": "Content creator", "country": "USA"},
    {"name": "Loren Gray", "follower_count": 41, "description": "Singer and influencer", "country": "USA"},
    {"name": "Marshmello", "follower_count": 40, "description": "DJ and producer", "country": "USA"},
    {"name": "Steve Aoki", "follower_count": 39, "description": "DJ and producer", "country": "USA"},
    {"name": "Bad Bunny", "follower_count": 220, "description": "Singer", "country": "Puerto Rico"},
    {"name": "Conor McGregor", "follower_count": 100, "description": "MMA Fighter", "country": "Ireland"},
    {"name": "Messi Fanpage", "follower_count": 98, "description": "Football Fan Page", "country": "Argentina"},
    {"name": "Ronaldo Fanpage", "follower_count": 96, "description": "Football Fan Page", "country": "Portugal"},
    {"name": "NASA Earth", "follower_count": 95, "description": "Science and nature", "country": "USA"},
    {"name": "Marvel", "follower_count": 140, "description": "Entertainment brand", "country": "USA"},
    {"name": "DC Comics", "follower_count": 130, "description": "Entertainment brand", "country": "USA"}
]
